[versions]
mod-dev-gradle-version="2.0.88"
registrate-version="MC1.21-1.3.0+55"
[plugins]
mod-dev-gradle={id="net.neoforged.moddev", version.ref="mod-dev-gradle-version"}
[libraries]
registrate={group="com.tterrag.registrate", name="Registrate", version.ref="registrate-version"}
[bundles]