# make by baka4n

name: Build Release All Mods

on :
  push:
    branches:
      - main
      - dev/**
    paths:
      - src/**
      - ap/src/**

env:
  git_branch: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.git_branch }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Data Build AG
        run: ./gradlew :Agricultural:dataBuild
      - name: Data Build Ad
        run: ./gradlew :Adventure:dataBuild
      - name: Data Build Deco
        run: ./gradlew :Deco:dataBuild
      - name: Data Build Vanilla++
        run: ./gradlew ":Vanilla Plus Plus:dataBuild"
      - name: Build All
        run: ./gradlew ":All In All:build"
      - name: Upload All
        uses: actions/upload-artifact@v4
        with:
          name: wild-wind-artifact
          path: |
            **/build/libs/