# make by baka4n

name: Cleanuo Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for current repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 8
          delete_workflow_pattern: 'build'
      - name: Deletr workflow runs for current repo by self
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_day: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: 'clean30dayworkflow'